# Configure regular AutoRecon options at the top of this file.
verbose = 1
output = "."
only-scans-dir = true
nmap = "-vv --reason --open -Pn -T4"

# Configure global options here.
[global]
password-wordlist = '/usr/share/wordlists/fasttrack.txt'

# Configure plugin options here.
[dirbuster]
tool = "gobuster"
threads = 100
ext = "txt,htm,html,php,asp,aspx,jsp,cgi,pl,py,sh,doc,docx,pdf,config,conf,xml,sql,shtml,log,inc,exe,cfm,c,bat,pem,ini,md,zip,tar,tar.gz,7z,bz2,yml,passwd,mf,mysql,pgsql,json,rb,phar,rst"
extras = '--quiet --timeout 7s --random-agent --discover-backup --status-codes-blacklist 400-599'
wordlist = [
	'/mnt/share/cheat/wordlists/webbust-noext.txt',
]
