#!/usr/bin/env zsh

# Creates a timestamped backup of files/folders passed in.
# source: https://github.com/mattmc3/zdotdir/blob/main/functions/bak

local now f
now=$(date +"%Y%m%d_%H%M%S")
for f in "$@"; do
  if [[ ! -e "$f" ]]; then
    echo "file not found: $f" >&2
    continue
  fi
  cp -R "$f" "$f".$now.bak
done
